export const CLICK_FOO = 'CLICK_FOO';
export const CALENDAR_INIT = 'CALENDAR_INIT';
export const CALENDAR_SUCCESS = 'CALENDAR_SUCCESS';
export const CALENDAR_FAILURE = 'CALENDAR_FAILURE';
export const DATE_SELECT_INIT = 'DATE_SELECT_INIT';
export const DATE_SELECT_SUCCESS = 'DATE_SELECT_SUCCESS';
export const DATE_SELECT_FAILURE = 'DATE_SELECT_FAILURE';
